services:
  app:
    image: fontanelle:${VERSION}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fontanelle.rule=Host(`fontanelleitalia.com`)
      - traefik.http.routers.fontanelle.tls=true
      - traefik.http.routers.fontanelle.tls.certresolver=myresolver
      - traefik.http.services.fontanelle.loadbalancer.server.port=3003
      - traefik.http.middlewares.fontanellemn-redirect.redirectregex.regex=^https?://fontanelle.mattianatali.com/(.*)
      - traefik.http.middlewares.fontanellemn-redirect.redirectregex.replacement=https://fontanelleitalia.com/$${1}
      - traefik.http.middlewares.fontanellemn-redirect.redirectregex.permanent=true
      - traefik.http.routers.fontanellemn.rule=Host(`fontanelle.mattianatali.com`)
      - traefik.http.routers.fontanellemn.tls=true
      - traefik.http.routers.fontanellemn.tls.certresolver=myresolver
      - traefik.http.routers.fontanellemn.middlewares=fontanellemn-redirect
