services:
  app:
    image: fontanelle:${VERSION}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fontanelle.rule=Host(`fontanelle.mattianatali.com`)
      - traefik.http.routers.fontanelle.tls=true
      - traefik.http.routers.fontanelle.tls.certresolver=myresolver
      - traefik.http.services.fontanelle.loadbalancer.server.port=3003
      - traefik.http.routers.fontanellemilano.rule=Host(`fontanellemilano.mattianatali.com`)
      - traefik.http.routers.fontanellemilano.tls=true
      - traefik.http.routers.fontanellemilano.tls.certresolver=myresolver
      - traefik.http.routers.fontanellemilano.middlewares=fontanellemilano-redirect
      - traefik.http.middlewares.fontanellemilano-redirect.redirectregex.regex=^https://fontanellemilano.mattianatali.com/(.*)
      - traefik.http.middlewares.fontanellemilano-redirect.redirectregex.replacement=https://fontanelle.mattianatali.com/$${1}
      - traefik.http.middlewares.fontanellemilano-redirect.redirectregex.permanent=true
