services:
  app:
    image: fontanelle:${VERSION}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.fontanelle.rule=Host(`fontanelle.mattianatali.com`)
      - traefik.http.routers.fontanelle.tls=true
      - traefik.http.routers.fontanelle.tls.certresolver=myresolver
      - traefik.http.services.fontanelle.loadbalancer.server.port=3003
